// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {
  if(license!=="None"){
    return `![github license](https://img.shields.io/badge/license-${license}-blue.svg)`
  } else {
    return ""
  }
}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {
  if(license!=="None"){
    return `\n* [License](#license)`
  } else {
    return ""
  }
  
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {
  if(license!=="None"){
    return `## License
    
    This project is licensed under the ${license} license`
  } else {
    return ""
  }
}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  return `# ${data.title}
${renderLicenseBadge(data.license)}
${renderLicenseLink(data.license)}
${renderLicenseSection(data.license)}
`;
}

function generateReadMe(answers) {
  return `# ${answers.title}

  ## Description
   ${answers.description}

  ## Table of Contents
   [Description](#description)
   [Installation](#installation)
   [Usage](#usage)
   [License](#license)
   [Contributing](#contributing)
   [Tests](#tests)
   [Questions](#questions)
   [username](#username)


  ## Installation
  ${answers.installation}  

  ## Usage
  ${answers.usage}

  ## License
  ${answers.license}

  ## Contributing
  ${answers.contributing}

  ## Tests
  ${answers.tests}

  ## Questions
 

  Find me on GitHub: ${answers.username}

  Email me with any questions: ${answers.email}

 _This README was generated by [README-generator](https://github.com/smurphy823/README-generator)_

  `;
}
module.exports = generateMarkdown;
module.exports = generateReadMe;
